# Generated by Django 4.2.4 on 2023-10-02 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_propertyimage_remove_property_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyimage',
            name='property',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='properties.property'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='photos',
            field=models.ImageField(upload_to='properties/'),
        ),
    ]
