# Generated by Django 4.2.4 on 2023-10-07 10:45

import django.core.validators
from django.db import migrations, models
import properties.helpers
import properties.models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_alter_propertyimage_photos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyimage',
            name='photos',
            field=models.ImageField(max_length=255, upload_to=properties.helpers.path_and_rename, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpeg', 'jpg']), properties.models.PropertyImage.validate_image]),
        ),
    ]
